### ISSUE TITLE
First page with logs.

### ISSUE THREAD

**Issue by hagenbrandt** [hagenbrandt/capstone-project#1]
# Value statement
As a **diver** \
I can **visit the first page and see three logs** \
so that I can **get inspired for my next dive.** \

# Description

- A list of three example logs. Each log contains an image, header, profile pic & name and four icons.

# Rules

- The logs are visible.
- Header, profile-pic and icons are links, that can be clicked (without getting a response)

# Tasks

- [x] Create the project

- [x] Create components for the logs.

- [x] Style the page.

# Size
Medium

**Comment by gadmel** [comment]
Dear Hagen, all the acceprence criteria are fulfilled.
If you try to use BEM-notation on your DiveLog page, I would call it differently. E.g.: `dive__log__user__link` I would call `dive-log__user__link`. Also for the better semantics I would make `.dive__log` a `<section>` or an `<article>`.  The three mocked elements are all div and are next to the `<footer>`-element inside of the `.root` element, I would recommend you to let these threee dive-logs to be in a scrollable `<main>` element.
