### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by hagenbrandt** [hagenbrandt/capstone-project#13]
# Value statement
# Description

- Add additional categories, create new icons and make them visible on the detail log.

# Tasks

- [x] Add new categories

- [x] Make validations for the form

- [x] Make new design for the form.

- [x] Create new icons for the new categories (and make them visible on detail log).

- [x] Create cam function

- [x] Upload cam picture

- [x] Handle two different uploads

- [x] refactor the form

- [x] create array for checkboxes

- [x] create checkboxes

# Size
Large
