### ISSUE TITLE
Detail log.

### ISSUE THREAD

**Issue by hagenbrandt** [hagenbrandt/capstone-project#2]
# Value statement
As a **diver** \
I can **click on the header of the log** \
so that I can **see the detail of the log** \

# Description

- The detail of the log with a pic, header, description, log-data and dive tags.

# Rules

- The header of the log on the first page is clickable.
- On click the detail page opens.

# Tasks

- [x] Design the page

- [x] Create the new page with a pic, header, description, log-data and dive tags.

- [x] Link the new page to the header.

# Size
Large.
