### ISSUE TITLE
log book.

### ISSUE THREAD

**Issue by hagenbrandt** [hagenbrandt/capstone-project#3]
# Value statement
As a **diver** \
I can **type in my log data** \
so that my **log data is visible** \

# Description

- A formular to type in the log data.

# Rules

- Type in only the allowed types of values.

# Tasks

- [x] Create a log book.

- [x] Design the page.

- [x] Create the formular for the log book.

# Size
Medium.
