### ISSUE TITLE
link book and list.

### ISSUE THREAD

**Issue by hagenbrandt** [hagenbrandt/capstone-project#4]
# Value statement
As a **diver** \
I can **push my log data** \
so that I can **see my log in the list** \

# Description

- Link of the log book to the list.

# Rules

- Push only the log data to the top of the list.

# Tasks

- [x] init useForm

- [x] init Firebase

- [x] Make the log book entries visible on the card.

- [x] use moment.js to count the duration

- [x] make truthy checkboxes visible as tags

# Size
Medium.
